# Generated by Django 4.1.4 on 2022-12-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(db_column='class', max_length=2)),
                ('date', models.DateField()),
                ('fare', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stations', models.IntegerField()),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'running_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
            ],
            options={
                'db_table': 'timeslot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('traveltime', models.IntegerField()),
                ('sl', models.IntegerField()),
                ('ac1', models.IntegerField()),
                ('ac2', models.IntegerField()),
                ('ac3', models.IntegerField()),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='id1_set', serialize=False, to='base.train')),
                ('sl', models.IntegerField(null=True)),
                ('ac1', models.IntegerField(null=True)),
                ('ac2', models.IntegerField(null=True)),
                ('ac3', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'train_status',
                'managed': False,
            },
        ),
    ]
